### ISSUE TITLE
Multiple days cases

### ISSUE THREAD

**Issue by IpadLi** [Yunfei-Ma-McMaster/one-night-werewolf-gpt-bot#1]
Hi,
This is a good project with a nice structure.

It seems in the current version, there is only one day in the `def start(self)`. Normally in real plays, the flow is: conversation -> vote -> check whether end -> conversation -> vote -> check whether end ...... So, the current version is a very simplified version. Will you consider a more complex version? For example, agents can die or be saved during game playing.

Thanks.

**Comment by IpadLi** [comment]
Oh, this is "one night werewolf" ...

**Comment by Yunfei-Ma-McMaster** [comment]
Thanks for reaching out. Yeah, it is **one night** werewolf where the project is focused on the day time conversation.
